### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#298]
https://dev-transitlog.hsldev.com/journey/20190422/060100/1069/1/0045_1258?vehicle=0045%2F1258&mapView=60.169017734741495%2C24.93632555007935%2C16&mapOverlays=Stop+radius&stop=1040271&date=2019-04-22&line=1069&route.routeId=1069&route.direction=1&tab=journeys&live=false&time=06%3A01%3A00&time_increment=1

**Comment by danieldunderfelt** [comment]
Will try to get this fixed asap.

**Comment by danieldunderfelt** [comment]
This should be resolved now.

**Comment by samijuhani** [comment]
Yep

**Comment by danieldunderfelt** [comment]
I actually noticed other crashes still, will fix.

**Comment by danieldunderfelt** [comment]
All crashes now fixed, as far as I know!

**Comment by samijuhani** [comment]
https://dev-transitlog.hsldev.com/journey/20190423/100800/2551/2/0012_929?vehicle=0012%2F929&mapView=60.19841670072346%2C24.93776321411133%2C13&stop=1173104&route.routeId=2551&route.direction=2&live=false&line=2551&time=10%3A40%3A21&date=2019-04-23 got this to crash still
