### ISSUE TITLE
Stops are not loading to map after "Palauta asetukset" has been pressed

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#445]
Needs F5 to get stops back to map

**Comment by danieldunderfelt** [comment]
This should now be fixed in dev and stage.

**Comment by samijuhani** [comment]
Loading of stops freezes ui now and takes longer than before, please check.

**Comment by danieldunderfelt** [comment]
Yes, stops are a problem, which should probably be a ticket of it's own.

**Comment by samijuhani** [comment]
Could not reproduce the freezing anymore. New ticket if feels a problem still.
